project:
  type: website

website:
  title: "NPD Network"
  navbar:
    background: "#c8635a"
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Explore"
        file: explore/index.qmd

  sidebar:
    - style: "docked"
      search: true
      background: light
      title: "Explore"
      contents:
        - explore/index.qmd
        - auto: explore/*

  page-navigation: true
  repo-url: https://github.com/banskt/npd-notes
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
