project:
  type: website

website:
  title: "NPD Network"
  navbar:
    background: "#C8635A"
    search: true
    left:
      - text: "Explore"
        file: explore/index.qmd
      - text: "Results"
        file: result/index.qmd

  sidebar:
    - title: "Explore"
      style: "docked"
      search: true
      background: light
      collapse-level: 1
      contents: 
        - explore/index.qmd
        - section: "Notebooks"
          contents:
            - auto: explore/*.ipynb
#
    - title: "Results"
      contents:
        - result/index.qmd
#
  page-navigation: true
  repo-url: https://github.com/banskt/nygc-notes
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
