project:
  type: website

website:
  title: "NPD Network"
  navbar:
    background: "#C8635A"
    search: true
    left:
      - text: "Notebooks"
        file: notebooks/index.qmd
      - text: "Resources"
        file: resources/index.qmd
      - text: "Reference"
        file: reference/index.qmd

  sidebar:
    - title: "Notebooks"
      style: "docked"
      search: true
      background: light
      collapse-level: 2
      contents: 
        - notebooks/index.qmd
        - section: "Subcategory"
          contents:
            - notebooks/explore/index.qmd
#
    - title: "Reference"
      contents:
        - reference/index.qmd
#
    - title: "Meetings"
      contents:
        - meetings/index.qmd
        - auto: meetings/*
#
  page-navigation: true
  repo-url: https://github.com/banskt/nygc-notes
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
